apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: controller
  newName: quay.io/avisied0/freeipa-operator
  newTag: dev-bcfa2528e28cd04e14cd245211f4fd709f8a83ef

namespace: freeipa
