---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        # https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: controller:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false

          command:
            - /manager
          args:
            - --leader-elect
            # FIXME Remove -debug for releases
            - -debug

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            limits:
              cpu: 100m
              memory: 80Mi
            requests:
              cpu: 100m
              memory: 60Mi

          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # TODO Set RELATED_IMAGE_FREEIPA from a configmap and
            #      inject here the value so the container image
            #      is managed from the configmap
            - name: RELATED_IMAGE_FREEIPA
              value: quay.io/freeipa/freeipa-openshift-container:latest
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
