---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: controller:latest
          # FIXME Remove imagaPullPolicy for releases
          imagePullPolicy: Always

          resources:
            limits:
              cpu: 100m
              memory: 80Mi
            requests:
              cpu: 100m
              memory: 60Mi

          command:
            - /manager
          args:
            - --enable-leader-election
            # FIXME Remove -debug for releases
            - -debug
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # TODO Set RELATED_IMAGE_FREEIPA from a configmap and
            #      inject here the value so the container image
            #      is managed from the configmap
            - name: RELATED_IMAGE_FREEIPA
              value: quay.io/freeipa/freeipa-openshift-container:latest
