apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "idmocp.redhat.com/v1alpha1",
          "kind": "IDM",
          "metadata": {
            "name": "idm-sample"
          },
          "spec": {
            "realm": "EXAMPLE.TESTING",
            "passwordSecret": "idm-sample",
            "resources": {
              "requests": {
                "cpu": "2000m",
                "memory": "3Gi"
              },
              "limits": {
                "cpu": "2000m",
                "memory": "4Gi"
              }
            },
            "volumeClaimTemplate": {
              "resources": {
                "requests": {
                  "storage": "10Gi"
                }
              },
              "volumeMode": "Filesystem",
              "accessModes": [
                "ReadWriteOnce"
              ]
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.17.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: freeipa-operator.v0.0.1-705c5f2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: IDM is the Schema for the idms API
      displayName: IDM
      kind: IDM
      name: idms.idmocp.redhat.com
      version: v1alpha1
      # The below is required by olm-crds-have-resources-test
      resources:
      - kind: Service
        version: v1
        name: idm-operator-webhook-service
      - kind: Service
        version: v1
        name: idm-operator-controller-manager-metrics-service
      - kind: Deployment
        version: v1
        name: idm-operator-controller-manager
      # The below is required by olm-spec-descriptors-test
      specDescriptors:
      - displayName: "Realm"
        description: "The Realm to manage by Freeipa"
        path: "realm"
      - displayName: "Secret"
        description: "Password secret; By default it is generated a Secret with random passwords"
        path: "passwordSecret"
      - displayName: "Resources"
        description: "Resource limit and request"
        path: "resources"
      - displayName: "volumeClaimTemplate"
        description: "Template for the persistence information to be used"
        path: "volumeClaimTemplate"
      # The below is required by olm-status-descriptors-test
      statusDescriptors:
      - displayName: "Secret Name"
        description: "The name for the Secret resource"
        path: "secretName"
  description: Deploy Freeipa in OpenShift
  displayName: Identity Management as a Service
  icon:
  # TODO Add icon and mediatype
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - config.openshift.io
          resources:
          - dnses
          verbs:
          - list
          - get
          - watch
        serviceAccountName: idm-operator-controller-manager
      deployments:
      - name: idm-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: RELATED_IMAGE_FREEIPA
                  value: quay.io/freeipa/freeipa-openshift-container:latest
                image: quay.io/avisied0/freeipa-operator:latest
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 80Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: idm-operator-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - list
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - get
          - update
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - idmocp.redhat.com
          resources:
          - idms
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - idmocp.redhat.com
          resources:
          - idms/finalizers
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - idmocp.redhat.com
          resources:
          - idms/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - list
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes/custom-host
          verbs:
          - create
        serviceAccountName: idm-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - freeipa
  - kerberos
  - pki
  - sso
  - idm
  links:
  - name: Freeipa Operator
    url: https://freeipa-operator.domain
  maintainers:
  - email: freeipa-users@lists.fedorahosted.org
    name: freeipa-users
  maturity: alpha
  provider:
    name: Red Hat
    url: https://www.redhat.com
  relatedImages:
  - image: quay.io/freeipa/freeipa-openshift-container:latest
    name: freeipa
  version: 0.0.1-705c5f2
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: idm-operator-controller-manager
    failurePolicy: Fail
    generateName: midm.kb.io
    rules:
    - apiGroups:
      - idmocp.redhat.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - idms
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-idmocp-redhat-com-v1alpha1-idm
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: idm-operator-controller-manager
    failurePolicy: Fail
    generateName: vidm.kb.io
    rules:
    - apiGroups:
      - idmocp.redhat.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - idms
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-idmocp-redhat-com-v1alpha1-idm
