apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: idm-operator-freeipa-role
rules:
- apiGroups:
  - ""
  resourceNames:
  - idm-operator-freeipa
  resources:
  - serviceaccount
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resourceNames:
  - idm-operator-freeipa
  resources:
  - securitycontextconstraints
  verbs:
  - use
