---
kind: DeploymentConfig
apiVersion: v1
metadata:
  # name: "${IPA_SERVER_SERVICE}"
  name: "freeipa"
  labels:
    # deploymentconfig: "${IPA_SERVER_SERVICE}"
    deploymentconfig: "freeipa"
spec:
  strategy:
    type: Recreate
    recreateParams:
      # timeoutSeconds: "${{TIMEOUT}}"
      timeoutSeconds: 300
  triggers:
  - type: ConfigChange
  # - type: ImageChange
  #   imageChangeParams:
  #     automatic: true
  #     containerNames:
  #     - "${IPA_SERVER_SERVICE}"
  #     from:
  #       kind: ImageStreamTag
  #       name: "${IPA_SERVER_IMAGE}"
  replicas: 1
  test: false
  selector:
    # deploymentconfig: "${IPA_SERVER_SERVICE}"
    deploymentconfig: "freeipa"
  template:
    metadata:
      # name: "${IPA_SERVER_SERVICE}"
      name: "freeipa"
      labels:
        # deploymentconfig: "${IPA_SERVER_SERVICE}"
        deploymentconfig: "freeipa"
    spec:
      volumes:
      # - name: "${IPA_SERVER_SERVICE}-data"
      #   persistentVolumeClaim:
      #     claimName: "${IPA_SERVER_SERVICE}"
      # - name: "${IPA_SERVER_SERVICE}-run"
      #   emptyDir: {}
      # - name: "${IPA_SERVER_SERVICE}-tmp"
      #   emptyDir: {}
      # - name: "${IPA_SERVER_SERVICE}-journal"
      #   emptyDir: {}
      - name: "freeipa-data"
        emptyDir: {}
      - name: "freeipa-run"
        emptyDir: {}
      - name: "freeipa-tmp"
        emptyDir: {}
      - name: "freeipa-journal"
        emptyDir: {}
      containers:
      - name: "freeipa"
        image: "freeipa/freeipa-server:fedora-32"
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 88
          protocol: TCP
        - containerPort: 88
          protocol: UDP
        - containerPort: 123
          protocol: UDP
        - containerPort: 389
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 464
          protocol: TCP
        - containerPort: 464
          protocol: UDP
        - containerPort: 636
          protocol: TCP
        env:
        # - name: IPA_SERVER_HOSTNAME
        #   value: "${IPA_SERVER_HOSTNAME}"
        # - name: IPA_SERVER_IP
        #   value: "${IPA_SERVER_IP}"
        # - name: IPA_SERVER_INSTALL_OPTS
        #   value: "${IPA_SERVER_INSTALL_OPTS}"
        # - name: PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: "${IPA_SERVER_SERVICE}-password"
        #       key: admin.password
        - name: IPA_SERVER_HOSTNAME
          value: "freeipa"
        # Review this one
        - name: IPA_SERVER_IP
          value: "${IPA_SERVER_IP}"
        # Review this one
        - name: IPA_SERVER_INSTALL_OPTS
          value: "${IPA_SERVER_INSTALL_OPTS}"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: "freeipa-password"
              key: admin.password
        args:
          # - "${COMMAND}"
          - ipa-server-install
        resources: {}
        volumeMounts:
          # - name: "${IPA_SERVER_SERVICE}-data"
          #   mountPath: "/data"
          # - name: "${IPA_SERVER_SERVICE}-run"
          #   mountPath: "/run"
          # - name: "${IPA_SERVER_SERVICE}-tmp"
          #   mountPath: "/tmp"
          # - name: "${IPA_SERVER_SERVICE}-journal"
          #   mountPath: "/var/log/journal"
          - name: "freeipa-data"
            mountPath: "/data"
          - name: "freeipa-run"
            mountPath: "/run"
          - name: "freeipa-tmp"
            mountPath: "/tmp"
          - name: "freeipa-journal"
            mountPath: "/var/log/journal"
        readinessProbe:
          exec:
            command:
              - "/usr/bin/systemctl"
              - status
              - ipa
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
      # serviceAccountName: "${SERVICE_ACCOUNT_USEROOT}"
      serviceAccountName: "freeipa"
      securityContext: {}
