---
kind: ImageStreamList
apiVersion: v1
metadata: {}
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: freeipa-server
    annotations:
      openshift.io/display-name: FreeIPA Server
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/display-name: FreeIPA Server on Fedora
        tags: freeipa, identity management
      from:
        kind: ImageStreamTag
        name: fedora-31
    - name: fedora-31
      annotations:
        openshift.io/display-name: FreeIPA Server on Fedora 31
        tags: freeipa, identity management
      from:
        kind: DockerImage
        name: freeipa/freeipa-server:fedora-31
    - name: fedora-30
      annotations:
        openshift.io/display-name: FreeIPA Server on Fedora 30
        tags: freeipa, identity management
      from:
        kind: DockerImage
        name: freeipa/freeipa-server:fedora-30
    - name: fedora-rawhide
      annotations:
        openshift.io/display-name: FreeIPA Server on Fedora rawhide
        tags: freeipa, identity management
      from:
        kind: DockerImage
        name: freeipa/freeipa-server:fedora-rawhide
    - name: centos-8
      annotations:
        openshift.io/display-name: FreeIPA Server on CentOS 8
        tags: freeipa, identity management
      from:
        kind: DockerImage
        name: freeipa/freeipa-server:centos-8
    - name: centos-7
      annotations:
        openshift.io/display-name: FreeIPA Server on CentOS 7
        tags: freeipa, identity management
      from:
        kind: DockerImage
        name: freeipa/freeipa-server:centos-7
    - name: rhel-7
      annotations:
        openshift.io/display-name: Identity Management Server on RHEL 7
        tags: idm, freeipa, identity management
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhel7/ipa-server

