---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: freeipa
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: "/opt/freeipa-server-data"

