---
kind: Secret
apiVersion: v1
metadata:
  # name: "${IPA_SERVER_SERVICE}-password"
  name: "freeipa-password"
stringData:
  # admin.password: "${IPA_ADMIN_PASSWORD}"
  admin.password: "administrator"
