apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: default
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - name: "selinux"
    data: |
      [selinux]
      container_manage_cgroup=1
  recommend: []
