package controllers

// IMDReconcilerError It represent the errors generated by our Reconciler class.
type IMDReconcilerError struct {
	desc string
}

func (e *IMDReconcilerError) Error() string {
	return e.desc
}

// NewInitializingManifest Create an error for manifests that fails at initialization.
func NewInitializingManifest(namespace string, kind string, name string) *IMDReconcilerError {
	return &IMDReconcilerError{
		desc: "The named '" + name + "' manifest of '" + kind + "' kind at '" + namespace + "' namespace was not initialized",
	}
}
