---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnses-role
rules:
  # Allow to retrieve the ingress domain
  - apiGroups: ["config.openshift.io"]
    resources:
      - ingresses
    verbs:
      - watch
      - list
      - get