---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: freeipa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: freeipa-role
subjects:
  - kind: ServiceAccount
    name: freeipa
