---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: freeipa-role
rules:
  - apiGroups:
      - ""
    resources:
      - "serviceaccount"
    verbs:
      - "use"
    resourceNames:
      - "idm-operator-freeipa"

  - apiGroups: ["security.openshift.io"]
    resources:
      - "securitycontextconstraints"
    verbs:
      - "use"
    resourceNames:
      - "idm-operator-freeipa"
