---
# https://docs.openshift.com/container-platform/4.5/authentication/managing-security-context-constraints.html
# https://kubernetes-security.info/
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: poc-003
  labels:
    app: poc-003
  annotations:
    kubernetes.io/description: poc-003 provides all features of the
      restricted SCC but allows users to run with any UID and any GID.
    release.openshift.io/create-only: "true"
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
  # Default capabilities anyuid
  - "SETUID"
  - "SETGID"
  - "FSETID"
  - "SETPCAP"
  - "DAC_OVERRIDE"
  - "NET_RAW"
  - "NET_BIND_SERVICE"
  - "SYS_CHROOT"
  - "KILL"
  - "AUDIT_WRITE"
  - "CHOWN"
  - "FOWNER"
  - "SETFCAP"

  # No default capabilities
  - "SYS_ADMIN"
  - "SYS_RESOURCE"
  - "MKNOD"
allowedUnsafeSysctls:
defaultAddCapabilities:
  # Default capabilities anyuid
  - "CHOWN"
  - "FOWNER"
  - "SETFCAP"

  - "SETPCAP"
  - "SETFCAP"
  - "SETUID"
  - "SETGID"
  - "DAC_OVERRIDE"
  - "NET_BIND_SERVICE"
  - "KILL"

  # No default capabilities
  - "SYS_ADMIN"
  - "SYS_RESOURCE"
  - "MKNOD"
fsGroup:
  type: RunAsAny
priority: 20
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:avisiedo-init-container:poc-003
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  - hostPath
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: poc-003
  labels:
    app: poc-003
automountServiceAccountToken: true
# ---
# https://kubernetes.io/docs/concepts/security/pod-security-standards/#what-s-the-difference-between-a-security-policy-and-a-security-context
# https://kubernetes.io/docs/concepts/policy/pod-security-policy/#create-a-policy-and-a-pod
# apiVersion: policy/v1beta1
# kind: PodSecurityPolicy
# metadata:
#   name: poc-003
#   labels:
#     app: poc-003
# spec:
#   privileged: false  # Don't allow privileged pods!
#   seLinux:
#     rule: RunAsAny
#   supplementalGroups:
#     rule: RunAsAny
#   runAsUser:
#     rule: RunAsAny
#   fsGroup:
#     rule: RunAsAny
#   volumes:
#     - configMap
#     - downwardAPI
#     - emptyDir
#     - persistentVolumeClaim
#     - projected
#     - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: poc-003
  labels:
    app: poc-003
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poc-003
  labels:
    app: poc-003
subjects:
  - kind: ServiceAccount
    name: poc-003
roleRef:
  kind: Role
  name: poc-003
  apiGroup: rbac.authorization.k8s.io
---
# create a new ClusterRole (since SCC’s are cluster scoped instead of namespace
# scoped) that will provide access to a given SCC
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poc-003
  labels:
    app: poc-003
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - poc-003
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: poc-003
  labels:
    app: poc-003
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: poc-003
subjects:
  - kind: ServiceAccount
    name: poc-003
    namespace: avisiedo-init-container
