# This file is not included in kustomize resources as it is
# used independently from mk/cert-manager.mk to automate the
# cert-manager operator installation in OpenShift
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager
  namespace: openshift-operators
  labels:
    operators.coreos.com/cert-manager.openshift-operators: ""
spec:
  name: cert-manager
  source: community-operators
  sourceNamespace: openshift-marketplace
  channel: stable
  installPlanApproval: Automatic
  startingCSV: cert-manager.v1.7.2
