---
- op: add
  path: /spec/install/spec/permissions/-
  value:
  - serviceAccountName: idm-operator-freeipa
    rules:
      - apiGroups: ["security.openshift.io"]
        resources:
          - "securitycontextconstraints"
        verbs:
          - "use"
        resourceNames:
          - freeipa
