---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: idmocp
subjects:
  - kind: ServiceAccount
    name: idmocp
roleRef:
  kind: Role
  name: idmocp
  apiGroup: rbac.authorization.k8s.io
