# Proof of Concept for hello world
#
# Quick Start:
#   export APP=poc-00; make app-delete app-deploy get-info
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: poc-00
  labels:
    app: poc-00
data:
  main.sh: |
    #!/bin/sh
    echo "Script: $0"
    while true; do sleep 1; done
---
apiVersion: v1
kind: Pod
metadata:
  name: poc-00
  labels:
    app: poc-00
spec:
  containers:
    - name: main
      image: docker.io/openshift/origin-cli:v4.0
      command: ["/opt/poc-00/main.sh"]
      volumeMounts:
        - name: scripts
          mountPath: /opt/poc-00

  initContainers:
    - name: init-hello-world
      image: hello-world:latest

  volumes:
    - name: scripts
      configMap:
        name: poc-00
        items:
          - key: "main.sh"
            path: "main.sh"
            mode: 0777
