# https://kubernetes.io/docs/concepts/services-networking/service/#external-ips
# https://docs.openshift.com/container-platform/4.4/networking/configuring_ingress_cluster_traffic/configuring-ingress-cluster-traffic-service-external-ip.html
# https://docs.openshift.com/container-platform/4.4/networking/configuring_ingress_cluster_traffic/configuring-externalip.html
---
apiVersion: v1
kind: Pod
metadata:
  name: poc-004-4a-client
  labels:
    app: poc-004-4a
    role: services
spec:
  serviceAccountName: poc-004
  # https://github.com/nicolaka/netshoot
  containers:
    - name: client
      image: quay.io/avisied0/netshoot
      command: ["cat"]
      stdin: true
---
apiVersion: v1
kind: Pod
metadata:
  name: poc-004-4a-services
  labels:
    app: poc-004-4a
    role: services
spec:
  serviceAccountName: poc-004
  # https://github.com/nicolaka/netshoot
  containers:
    - name: client
      image: quay.io/avisied0/netshoot
      command: ["cat"]
      stdin: true

    - name: http
      image: quay.io/freeipa/freeipa-operator:poc-004
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "80"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - name: http-tcp
          containerPort: 80
          # hostPort: 80
          protocol: TCP

    - name: https
      image: quay.io/freeipa/freeipa-operator:poc-004
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "443"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 443
          # hostPort: 443
          protocol: TCP

    - name: ldap
      image: quay.io/freeipa/freeipa-operator:poc-004
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "389"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 389
          # hostPort: 389
          protocol: TCP

    - name: ldaps
      image: quay.io/freeipa/freeipa-operator:poc-004
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "636"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 636
          # hostPort: 636
          protocol: TCP
    - name: kerberos-tcp
      image: quay.io/freeipa/freeipa-operator:poc-004
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "88"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 88
          # hostPort: 88
          protocol: TCP

    - name: kerberos-admin-tcp
      image: quay.io/freeipa/freeipa-operator:poc-004
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "464"
        - name: "ECHO_PROTOCOL"
          value: "tcp"
      ports:
        - containerPort: 464
          # hostPort: 464
          protocol: TCP

    - name: kerberos-udp
      image: quay.io/freeipa/freeipa-operator:poc-004
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "88"
        - name: "ECHO_PROTOCOL"
          value: "udp"
      ports:
        - containerPort: 88
          # hostPort: 88
          protocol: UDP

    - name: kerberos-admin-udp
      image: quay.io/freeipa/freeipa-operator:poc-004
      securityContext:
        capabilities:
          add:
            - NET_BIND_SERVICE
      env:
        - name: "ECHO_PORT"
          value: "464"
        - name: "ECHO_PROTOCOL"
          value: "udp"
      ports:
        - containerPort: 464
          # hostPort: 464
          protocol: UDP
---
# Allocated floating IP 10.0.133.188
# The initial floating IP for apps: 10.0.135.189
apiVersion: v1
kind: Service
metadata:
  name: poc-004-4a-tcp
  labels:
    app: poc-004-4a
spec:
  type: NodePort
  externalIPs:
    # - "10.0.133.188"
    - "192.168.130.12"
  selector:
    app: poc-004-4a
  ports:
    - name: ldap
      protocol: TCP
      port: 389
    - name: ldaps
      protocol: TCP
      port: 636
    - name: kerberos-tcp
      protocol: TCP
      port: 88
    - name: kerberos-admin-tcp
      protocol: TCP
      port: 464
---
apiVersion: v1
kind: Service
metadata:
  name: poc-004-4a-udp
  labels:
    app: poc-004-4a
spec:
  type: NodePort
  externalIPs:
    # - "10.0.133.188"
    - "192.168.130.12"
  selector:
    app: poc-004-4a
  ports:
    - name: kerberos-udp
      protocol: UDP
      port: 88
    - name: kerberos-admin-udp
      protocol: UDP
      port: 464
---
apiVersion: v1
kind: Service
metadata:
  name: poc-004-4a-web
  labels:
    app: poc-004-4a
spec:
  type: NodePort
  externalIPs:
    # - "10.0.133.188"
    - "192.168.130.12"
  selector:
    app: poc-004-4a
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 31080
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
# ---
# https://docs.openshift.com/container-platform/4.4/networking/routes/route-configuration.html
# apiVersion: v1
# kind: Route
# metadata:
#   name: poc-004-4a
#   labels:
#     app: poc-004-4a
# spec:
#   subdomain: freeipa
#   port:
#     targetPort: 443
#   to:
#     kind: Service
#     name: poc-004-4a-web
#   tls:
#     insecureEdgeTerminationPolicy: Redirect
#     termination: passthrough
