---
apiVersion: idmocp.redhat.com/v1alpha1
kind: IDM
metadata:
  name: idm-sample
spec:
  # Add fields here
  realm: bar
  passwordSecret: idm-sample
  resources:
    requests:
      cpu: "1500m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"
  volumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeMode: Filesystem
    selector:
      matchLabels:
        app: freeipa
