---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 10-enable-container-manage-cgroup-sebool
spec:
  config:
    ignition:
      version: 2.2.0
      systemd:
        units:
          - name: setsebool-container-manage-cgroup.service
            enabled: true
            contents: |
              [Unit]
              Before=kubelet.service
              [Service]
              Type=oneshot
              ExecStart=setsebool container_manage_cgroup true
              RemainAfterExit=yes
              [Install]
              WantedBy=multi-user.target
