---
apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: container-manage-cgroup
spec:
  profile:
    - data: |
        [main]
        summary=A custom OpenShift sebool profile
        [selinux]
        container_manage_cgroup=1
      name: enable-container-manage-cgroup
  recommend: []
